export const APP_CONSTANTS = {
  API_BASE_PATH: '/api',
  API_VERSION: 'v1',
  APP_NAME: 'FitFIXto Backend',
} as const;

export const API_PREFIX = `${APP_CONSTANTS.API_BASE_PATH}/${APP_CONSTANTS.API_VERSION}`;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const RATE_LIMIT_CONFIG = {
  WINDOW_MS: 15 * 60 * 1000,
  MAX_REQUESTS: process.env.NODE_ENV === 'production' ? 300 : 2000,
  ADMIN_LOGIN_MAX_REQUESTS: 5,
} as const;
